FROM gcr.io/wise-cycling-267806/coverage

RUN ln -s /mnt/genome/snv/alignment/normal/normal.sorted.dup.recal.metric.insertSize.tsv /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.sorted.dup.recal.metric.insertSize.histo.pdf /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.sorted.dup.recal.metric.insertSize.tsv /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.sorted.dup.recal.metric.insertSize.histo.pdf /home/bioinfo/snv/alignment/tumour/
