FROM gcr.io/wise-cycling-267806/recal

RUN ln -s /mnt/genome/snv/alignment/normal/normal.mosdepth.global.dist.txt /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.mosdepth.region.dist.txt /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.mosdepth.summary.txt /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.regions.bed.gz /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.regions.bed.gz.csi /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.thresholds.bed.gz /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.thresholds.bed.gz.csi /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.mosdepth.global.dist.txt /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.mosdepth.region.dist.txt /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.mosdepth.summary.txt /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.regions.bed.gz /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.regions.bed.gz.csi /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.thresholds.bed.gz /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.thresholds.bed.gz.csi /home/bioinfo/snv/alignment/tumour/
