FROM gcr.io/wise-cycling-267806/insert

RUN ln -s /mnt/genome/snv/alignment/normal/normal.sorted.dup.recal.metric.alignment.tsv /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.sorted.dup.recal.metric.alignment.tsv /home/bioinfo/snv/alignment/tumour/
