FROM gcr.io/wise-cycling-267806/fixmates

RUN ln -s /mnt/genome/snv/alignment/normal/normal.sorted.dup.bam /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.sorted.dup.bai /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.sorted.dup.metrics /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.sorted.dup.bam /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.sorted.dup.bai /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.sorted.dup.metrics /home/bioinfo/snv/alignment/tumour/
