FROM gcr.io/wise-cycling-267806/snv

RUN ln -s /mnt/genome/snv/alignment/normal/normal.matefixed.bam /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/normal/normal.matefixed.bai /home/bioinfo/snv/alignment/normal/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.matefixed.bam /home/bioinfo/snv/alignment/tumour/
RUN ln -s /mnt/genome/snv/alignment/tumour/tumour.matefixed.bai /home/bioinfo/snv/alignment/tumour/